services:
  - type: web
    name: autovendor-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TAVILY_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: APITEMPLATE_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: GROQ_TEMPERATURE
        value: "0.3"
      - key: PYTHON_VERSION
        value: "3.12.0"
